### ISSUE TITLE
Create features common to all charts

### ISSUE THREAD

**Issue by antw** [quintel/refresh#34]
- [ ] **Unit formatting**: Values within a chart should be formatted consistently in the same unit and order of magnitude (see #7)
- [ ] **Tooltips**: If not already supported by the choice of chart library, we need to support tooltips for elements within the chart. See #33.
- [ ] **Legend**: A legend must be drawn representing each unique series in the chart. Clicking on a legend item should hide the series in the chart. See "Hidden series" in #32.
- [ ] **Description button**: A description button allows the visitor to expand a more detailed description of the chart, if one is available.
- [ ] **Auto-size axis (nice-to-have):** Our current D3 charts require that a pre-defined amount of space be set aside in which the axis can be drawn. For example, we may decide that a stacked bar requires 40px of space for the axis. This fails to account for values which require more or less space. If using Visx to create charts, it would be nice to find a way to determine how much space is needed by the axis dynamically. See https://github.com/quintel/etmodel/issues/3123 for an example.
