### ISSUE TITLE
Create ChartChrome component, and sub-components

### ISSUE THREAD

**Issue by antw** [quintel/refresh#37]
In previous sprints, investigations were done into the options we have for charting data in the refresh. It was decided that Visx/D3 are likely the most promising; while it takes more time to get a new chart up and running, these libraries provide us with greater flexibility.

My experiments so far were to create a custom stacked bar chart and area chart with Visx. The next step is to make this generic with a `ChartChrome` component, and sub-components that render the chart content.

### `ChartChrome` component

* Receives chart data in a common format.
* Performs filtering on the data (to hide or highlight series)
* Draws axis.
* Draws a legend.

The component will be a reusable base for many custom charts.

Work on this has already begun but is currently limited to a single linear y-axis, and a band x-axis. A band x-axis will be insufficient for some area and line data, which need a linear scale (either with numeric values for cost-capacity charts, or date values for hourly charts). While this is easy enough to do in JS, I'm still figuring out how to type this correctly with TypeScript since ScaleBand and ScaleLinear don't overlap, nor does D3 have a way to determine what type of scale you have after its creation.

It would be nice to add support for a [Brush](https://airbnb.io/visx/brush) when using linear x-scales, and better support for tooltips and stacking.

### Sub-components

Within `ChartChrome` will exist one or more child sub-components that receive and render the prepared data. These may include:

* `Bars` – render bars, with or without stacks and/or groups
* `Areas` – render areas, with or without stacks
* `Lines` – render lines

### Tasks

- [x] Move chart experiments into the real app
- [x] Write tests
- [x] Complete the `Area` component
- [x] Add a `Lines` component or build in support to the `Area` component.
- [ ] Add support for continuous scales on the x-axis.
- [ ] Animate axes
- [ ] Add / improve support for groups within the `Bars` component
- [ ] Add support for tooltips (either per-series, or per-stack/x-axis value).
